windows ödev/Pages/Charts.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using windows_ödev.Data;
using windows_ödev.Models.Domain;
namespace windows_ödev.Pages
{
    public class ChartsModel : PageModel
    {

        private readonly RazorPagesDemoDbContext dbContext;

        public ChartsModel(RazorPagesDemoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public string GenderDistributionJson { get; set; }
        public string AgeAveragesJson { get; set; }

        public void OnGet()
        {
            var genderDistribution = GetGenderDistribution();
            GenderDistributionJson = JsonSerializer.Serialize(genderDistribution);

            var ageAverages = GetAgeAverages();
            AgeAveragesJson = JsonSerializer.Serialize(ageAverages);
        }

        private Dictionary<string, double> GetGenderDistribution()
        {
            var genderDistribution = new Dictionary<string, double>();
            int totalCount = dbContext.Persons.Count();
            int maleCount = dbContext.Persons.Count(p => p.Gender == "Erkek");
            int femaleCount = dbContext.Persons.Count(p => p.Gender == "Kadin");

            genderDistribution["Erkek"] = Math.Round((double)maleCount / totalCount * 100,2);
            genderDistribution["Kadin"] = Math.Round((double)femaleCount / totalCount * 100,2);


            return genderDistribution;
        }

        private Dictionary<string, double> GetAgeAverages()
        {
            var ageAverages = new Dictionary<string, double>();

            var ageGroups = new List<Tuple<int, int>>()
            {
                new Tuple<int, int>(0, 15),
                new Tuple<int, int>(15, 30),
                new Tuple<int, int>(30, 45),
                new Tuple<int, int>(45, int.MaxValue)
            };

            foreach (var group in ageGroups)
            {
                var ageRange = group.Item2 == int.MaxValue ? "45+" : $"{group.Item1}-{group.Item2}";

                var personsInGroup = dbContext.Persons
                    .Where(p => p.Age >= group.Item1 && p.Age < group.Item2);

                var ageAverage = personsInGroup.Any()
                    ? personsInGroup.Average(p => p.Age)
                    : 0;

                ageAverages[ageRange] = Math.Round(ageAverage,2);
            }

            return ageAverages;
        }

    }

}

windows ödev/Pages/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using windows_ödev.Data;
using windows_ödev.Models.ViewModels;

namespace windows_ödev.Pages
{
    public class EditModel : PageModel
    {

        private readonly RazorPagesDemoDbContext dbContext;

        [BindProperty]
        public EditPersonViewModel EditPersonViewModel { get; set; }
        public EditModel(RazorPagesDemoDbContext dbContext) 
        {
        
            this.dbContext = dbContext;
        }  
        public void OnGet(Guid id)
        {
            var person = dbContext.Persons.Find(id);

            if(person != null)
            {
                // Convert Domain Model to View Model
                EditPersonViewModel = new EditPersonViewModel()
                {
                    Id = person.Id,
                    Name = person.Name,
                    Surname = person.Surname,
                    BirthDate = person.BirthDate,
                    Gender = person.Gender,
                    Age = person.Age,
                    PhotoData = person.PhotoData,
                    PhotoFile = person.PhotoFile,
                };
            }
        }

        public void OnPostUpdate()
        {
            if(EditPersonViewModel != null)
            {
                var existingPerson = dbContext.Persons.Find(EditPersonViewModel.Id);


            
                if(existingPerson != null)
                {
                    var today = DateTime.Now;

                    int age = today.Year - EditPersonViewModel.BirthDate.Year;
                    int monthDiff = today.Month - EditPersonViewModel.BirthDate.Month;
                    if (monthDiff < 0 || monthDiff == 0 && today.Day < EditPersonViewModel.BirthDate.Day)
                    {
                        age--;
                    }
                    EditPersonViewModel.Age = age;

                    // Convert ViewModel to DomainModel

                    existingPerson.Id = EditPersonViewModel.Id;
                    existingPerson.Name = EditPersonViewModel.Name;
                    existingPerson.Surname = EditPersonViewModel.Surname;
                    existingPerson.BirthDate = EditPersonViewModel.BirthDate;
                    existingPerson.Gender = EditPersonViewModel.Gender;
                    existingPerson.Age = EditPersonViewModel.Age;
                    existingPerson.PhotoFile = EditPersonViewModel.PhotoFile;


                    
                    byte[] bytes = null;

                    if (existingPerson.PhotoFile != null)
                    {
                        using (Stream fs = existingPerson.PhotoFile.OpenReadStream())
                        {
                            using (BinaryReader br = new BinaryReader(fs))
                            {
                                bytes = br.ReadBytes((Int32)fs.Length);
                            }
                            existingPerson.PhotoData = Convert.ToBase64String(bytes, 0, bytes.Length);
                        }
                    }


                    if (string.IsNullOrEmpty(existingPerson.Name) || string.IsNullOrEmpty(existingPerson.Surname) || string.IsNullOrEmpty(existingPerson.Gender) || DateTime.MinValue == existingPerson.BirthDate)
                    {
                        ViewData["AlertMessage"] = "Tum bilgilerinizi giriniz.";
                        return;
                    }


                    if (existingPerson.BirthDate > DateTime.Now)
                    {
                        ViewData["AlertMessage"] = "Dogum tarihiniz, bugunun tarihinden ileri bir tarih olamaz.";
                        return;
                    }

                    if (today.Year - existingPerson.BirthDate.Year >= 120)
                    {
                        ViewData["AlertMessage"] = "Dogum tarihiniz cok eski bir tarih olamaz.";
                        return;
                    }

                    dbContext.SaveChanges();

                    ViewData["Message"] = "Başarıyla Güncellendi.";
                }
            
            
            }


        }

        public IActionResult OnPostDelete()
        {
            var existingPerson = dbContext.Persons.Find(EditPersonViewModel.Id);

            if(existingPerson != null)
            {
                dbContext.Persons.Remove(existingPerson);
                dbContext.SaveChanges();

                return RedirectToPage("/Tablo");
            }

            return Page();
        }
    }
}

windows ödev/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace windows_ödev.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

windows ödev/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using windows_ödev.Data;
using windows_ödev.Models.Domain;
using windows_ödev.Models.ViewModels;

namespace windows_ödev.Pages
{
    public class IndexModel : PageModel
    {

        private readonly RazorPagesDemoDbContext dbContext;

        public IndexModel(RazorPagesDemoDbContext dbContext)
        {
            this.dbContext = dbContext;
        }


        [BindProperty]
        public PersonViewModel AddPersonRequest { get; set; }




        public void OnGet()
        {
           
        }


        public void OnPost()
        {
            // Convert ViewModel to DomainModel
            var personDomainModel = new Person
            {
                Name = AddPersonRequest.Name,
                Surname = AddPersonRequest.Surname,
                BirthDate = AddPersonRequest.BirthDate,
                Gender = AddPersonRequest.Gender,
                PhotoFile = AddPersonRequest.PhotoFile
            };

            byte[] bytes = null;

            if(AddPersonRequest.PhotoFile != null)
            {
                using (Stream fs = personDomainModel.PhotoFile.OpenReadStream())
                {
                    using (BinaryReader br = new BinaryReader(fs))
                    {
                        bytes = br.ReadBytes((Int32)fs.Length);
                    }
                    personDomainModel.PhotoData = Convert.ToBase64String(bytes, 0, bytes.Length);
                }
            }



            var today = DateTime.Now;


            if (string.IsNullOrEmpty(personDomainModel.Name) || string.IsNullOrEmpty(personDomainModel.Surname) || string.IsNullOrEmpty(personDomainModel.Gender) || DateTime.MinValue == personDomainModel.BirthDate)
            {
                ViewData["AlertMessage"] = "Tum bilgilerinizi giriniz.";
                return;
            }


            if (personDomainModel.BirthDate > DateTime.Now)
            {
                ViewData["AlertMessage"] = "Dogum tarihiniz, bugunun tarihinden ileri bir tarih olamaz.";
                return;
            }

            if (today.Year - personDomainModel.BirthDate.Year >= 120)
            {
                ViewData["AlertMessage"] = "Dogum tarihiniz cok eski bir tarih olamaz.";
                return;
            }


            int age = today.Year - personDomainModel.BirthDate.Year;
            int monthDiff = today.Month - personDomainModel.BirthDate.Month;
            if(monthDiff < 0 || monthDiff == 0 && today.Day < personDomainModel.BirthDate.Day)
            {
                age--;
            }

            personDomainModel.Age = age;
            dbContext.Persons.Add(personDomainModel);
            dbContext.SaveChanges();

            ViewData["Message"] = "Başarıyla eklendi.";



        }


}
}

windows ödev/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace windows_ödev.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

windows ödev/Pages/Tablo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Security.Principal;
using System.Text.Json;
using windows_ödev.Data;
using windows_ödev.Models.Domain;
using Microsoft.Extensions.Configuration;

namespace windows_ödev.Pages
{
    public class TabloModel : PageModel
    {


        private readonly RazorPagesDemoDbContext dbContext;
        private readonly IConfiguration Configuration;

        public TabloModel(RazorPagesDemoDbContext dbContext, IConfiguration configuration)
        {
            this.dbContext = dbContext;
            Configuration = configuration;
        }

       //public List<Models.Domain.Person> Persons { get; set; }
        public PaginatedList<Person> Persons { get; set; }

        public string NameSort { get; set; }
        public string SurnameSort { get; set; }
        public string DateSort { get; set; }
        public string AgeSort { get; set; }
        public string GenderSort { get; set; }
        public string CurrentFilter { get; set; }
        public string CurrentSort { get; set; }




        //public void OnGet()
        //{
        //    Persons = dbContext.Persons.ToList();
        //}

        public async Task OnGetAsync(string sortOrder, string currentFilter, string searchString, int? pageIndex)
        {
            CurrentSort = sortOrder;

            // using System;
            NameSort = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            DateSort = sortOrder == "Date" ? "date_desc" : "Date";
            AgeSort = sortOrder == "Age" ? "age_desc" : "Age";
            GenderSort = sortOrder == "Gender" ? "gender_desc" : "Gender";
            SurnameSort = sortOrder == "Surname" ? "surname_desc" : "Surname";

            if (searchString != null)
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            CurrentFilter = searchString;

            IQueryable<Person> person = from s in dbContext.Persons
                                            select s;


            if (!String.IsNullOrEmpty(searchString))
            {
                person = person.Where(s => s.Name.Contains(searchString)
                                       || s.Surname.Contains(searchString)
                                       || s.Age.ToString().Contains(searchString)
                                       || s.Gender.Contains(searchString)
                                       || s.BirthDate.Date.ToString().Contains(searchString)
                                       );
            }


            switch (sortOrder)
            {

                case "name_desc":
                    person = person.OrderByDescending(s => s.Name);
                    break;
                case "Date":
                    person = person.OrderBy(s => s.BirthDate);
                    break;
                case "date_desc":
                    person = person.OrderByDescending(s => s.BirthDate);
                    break;
                case "Age":
                    person = person.OrderBy(s => s.Age);
                    break;
                case "age_desc":
                    person = person.OrderByDescending(s => s.Age);
                    break;
                case "Gender":
                    person = person.OrderBy(s => s.Gender);
                    break;
                case "gender_desc":
                    person = person.OrderByDescending(s => s.Gender);
                    break;
                case "Surname":
                    person = person.OrderBy(s => s.Surname);
                    break;
                case "surname_desc":
                    person = person.OrderByDescending(s => s.Surname);
                    break;
                default:
                    person = person.OrderBy(s => s.Name);
                    break;
            }

            //Persons = await person.AsNoTracking().ToListAsync();
            var pageSize = Configuration.GetValue("PageSize", 4);
            Persons = await PaginatedList<Person>.CreateAsync(
                person.AsNoTracking(), pageIndex ?? 1, pageSize);


        }



    }
}

windows ödev/Pages/Charts.cshtml
@page
@model windows_ödev.Pages.ChartsModel
@{
    ViewData["Title"] = "Cinsiyet ve Yaş Dağılımı";
}

<h2>Cinsiyet ve Yaş Dağılımı</h2><br /><br />
<div style="display: flex;">
    <div style="flex: 1;">
        <canvas id="genderChart" width="400" height="400"></canvas>
    </div>
    <div style="flex: 1; margin-right: 100px;">
        <canvas id="ageChart" width="400" height="400"></canvas>
    </div>
</div>

@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script>
        var genderDistribution = @Html.Raw(Model.GenderDistributionJson);
        var ageAverages = @Html.Raw(Model.AgeAveragesJson);

        var genderCtx = document.getElementById('genderChart').getContext('2d');
        var genderChart = new Chart(genderCtx, {
            type: 'pie',
            data: {
                labels: Object.keys(genderDistribution),
                datasets: [{
                    data: Object.values(genderDistribution),
                    backgroundColor: [
                        'rgba(54, 162, 235, 0.5)',
                        'rgba(255, 99, 132, 0.5)'
                    ],
                    borderColor: [
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 99, 132, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: true
            }
        });

        var ageCtx = document.getElementById('ageChart').getContext('2d');
        var ageChart = new Chart(ageCtx, {
            type: 'bar',
            data: {
                labels: Object.keys(ageAverages),
                datasets: [{
                    label: 'Yaş Ortalaması',
                    data: Object.values(ageAverages),
                    backgroundColor: 'rgba(54, 162, 235, 0.5)',
                    borderColor: 'rgba(54, 162, 235, 1)',
                    borderWidth: 2
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: true,
                scales: {
                    y: {
                        beginAtZero: true,
                        grid: {
                            color: 'rgba(0, 0, 0, 0.1)' // Y ekseni
                        },
                        ticks: {
                            color: 'rgba(0, 0, 0, 0.8)' // Y eksenindeki rakamlar
                        }
                    },
                    x: {
                        grid: {
                            color: 'rgba(0, 0, 0, 0.1)'
                        },
                        ticks: {
                            color: 'rgba(0, 0, 0, 0.8)'
                        }
                    }
                }
            }
        });
    </script>
}

windows ödev/Pages/Edit.cshtml
@page "/Tablo/Edit/{id:guid}"
@model windows_ödev.Pages.EditModel
@{
    var message = ViewData["Message"]?.ToString();
    var alertMessage = ViewData["AlertMessage"]?.ToString();
}
<h1 class="mb-3"> Profili Güncelle </h1>

<form method="POST" class="m-4" enctype="multipart/form-data">

    @if (!string.IsNullOrWhiteSpace(message))
    {
        <div class="alert alert-success" role="alert">
            @message
        </div>
    }
    @if (!string.IsNullOrWhiteSpace(alertMessage))
    {
        <div class="alert alert-danger" role="alert">
            @alertMessage
        </div>
    }

<div class="mb-3">
    <label for="Name" class="form-label">Id:</label>
    <input type="text" class="form-control" id="Id" name="Id" asp-for="EditPersonViewModel.Id" readonly>
</div>

<div class="mb-3">
    <label for="Name" class="form-label">Ad:</label>
        <input type="text" class="form-control" id="Name" name="Name" asp-for="EditPersonViewModel.Name">
</div>

<div class="mb-3">
    <label for="Surname" class="form-label">Soyad:</label>
        <input type="text" class="form-control" id="Surname" name="Surname" asp-for="EditPersonViewModel.Surname">
</div>

<div class="mb-3">
    <label for="BirthDate" class="form-label">Doğum Tarihi:</label>
        <input type="date" class="form-control" id="BirthDate" name="BirthDate" asp-for="EditPersonViewModel.BirthDate">
</div>


<label for="Gender" class="form-label" style="margin-top: 5px;">Cinsiyet:</label>
<div class="form-check">
        <input class="form-check-input" type="radio" id="erkek" name="Gender" value="Erkek" asp-for="EditPersonViewModel.Gender">
    <label class="form-check-label" for="erkek">Erkek</label>
</div>
<div class="form-check">
        <input class="form-check-input" type="radio" id="kadin" name="Gender" value="Kadin" asp-for="EditPersonViewModel.Gender">
    <label class="form-check-label" for="kadin">Kadın</label>
</div>


<div class="form-group" style="margin-top: 16px;">
    <label for="photo">Fotoğraf Seçin:</label>
        <input type="file" id="photo" name="PhotoFile" class="form-control-file" accept="image/*"/>
</div>
<div class="mb-3 d-flex justify-content-between">
    <button type="submit" class="btn btn-primary" style="margin-top: 8px;" asp-page-handler="Update">Güncelle</button>
    <button type="submit" class="btn btn-danger" style="margin-top: 8px;" asp-page-handler="Delete">Sil</button>
</div>


</form>

windows ödev/Pages/Index.cshtml
@page
@using Microsoft.AspNetCore.Http
@using System.Text.Json
@using System.Text.Json.Serialization
@model IndexModel
@{
    ViewData["Title"] = "Form";
    var message = ViewData["Message"]?.ToString();
    var alertMessage = ViewData["AlertMessage"]?.ToString();
}


<form method="POST" class="m-4" enctype="multipart/form-data">

    @if (!string.IsNullOrWhiteSpace(message))
    {
        <div class="alert alert-success" role="alert">
            @message
        </div>
    }
    @if (!string.IsNullOrWhiteSpace(alertMessage))
    {
        <div class="alert alert-danger" role="alert">
            @alertMessage
        </div>
    }
    <div class="mb-3">
        <label for="Name" class="form-label">Ad:</label>
        <input type="text" class="form-control" id="Name" name="Name">
    </div>

    <div class="mb-3">
        <label for="Surname" class="form-label">Soyad:</label>
        <input type="text" class="form-control" id="Surname" name="Surname">
    </div>

    <div class="mb-3">
        <label for="BirthDate" class="form-label">Doğum Tarihi:</label>
        <input type="date" class="form-control" id="BirthDate" name="BirthDate">
    </div>

    <label for="Gender" class="form-label" style="margin-top: 5px;">Cinsiyet:</label>
    <div class="form-check">
        <input class="form-check-input" type="radio" id="erkek" name="Gender" value="Erkek">
        <label class="form-check-label" for="erkek">Erkek</label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" id="kadin" name="Gender" value="Kadin">
        <label class="form-check-label" for="kadin">Kadın</label>
    </div>
    <div class="form-group" style="margin-top: 16px;">
        <label for="photo">Fotoğraf Seçin:</label>
        <input type="file" id="photo" name="PhotoFile" class="form-control-file" accept="image/*" />


    </div>


    <button type="submit" class="btn btn-primary" style="margin-top: 8px;">Gönder</button>


</form>

windows ödev/Pages/Tablo.cshtml
@page
@model windows_ödev.Pages.TabloModel
@{
}
@{
    var prevDisabled = !Model.Persons.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.Persons.HasNextPage ? "disabled" : "";
}

@if(Model.Persons != null && Model.Persons.Any())
{
    <form asp-page="./Tablo" method="get">
        <div class="form-actions no-color">
            <p>
                <input type="text" name="SearchString" value="@Model.CurrentFilter" />
                <input type="submit" value="Search" class="btn btn-primary" /> |
                <a asp-page="./Tablo" style="color: black;">Back to full List</a>

            </p>
        </div>
    </form>
    
    <table class="table">
        <thead>
            <tr>
                <th>Fotoğraf</th>

                <th>
                    <a asp-page="./Tablo" style="color: black;" asp-route-sortOrder="@Model.NameSort"
                        asp-route-currentFilter="@Model.CurrentFilter">
                    @Html.DisplayNameFor(model => model.Persons[0].Name) 
                       
                </a>
                </th>
                <th>
                    <a asp-page="./Tablo" style="color: black;" asp-route-sortOrder="@Model.SurnameSort"
                        asp-route-currentFilter="@Model.CurrentFilter">
                        @Html.DisplayNameFor(model => model.Persons[0].Surname)
                    </a>
                </th>
                <th>
                    <a asp-page="./Tablo" style="color: black;" asp-route-sortOrder="@Model.DateSort"
                        asp-route-currentFilter="@Model.CurrentFilter">
                        @Html.DisplayNameFor(model => model.Persons[0].BirthDate)
                    </a>
                </th>
                <th>
                    <a asp-page="./Tablo" style="color: black;" asp-route-sortOrder="@Model.AgeSort"
                        asp-route-currentFilter="@Model.CurrentFilter">
                        @Html.DisplayNameFor(model => model.Persons[0].Age)
                    </a>
                </th>

                <th>
                    <a asp-page="./Tablo" style="color: black;" asp-route-sortOrder="@Model.GenderSort"
                       asp-route-currentFilter="@Model.CurrentFilter">
                        @Html.DisplayNameFor(model => model.Persons[0].Gender)
                    </a>
                </th>

                <th></th>

            </tr>
        </thead>
        <tbody>
            @foreach(var person in Model.Persons)
            {
                <tr>
                    @if (person.PhotoData != null)
                    {
                        <td><img src="data:image;base64,@person.PhotoData" alt="Avatar" width="80" height="80" style="border-radius: 50%" /></td>
                    }
                    else
                    {
                        <td><img src="/img/indir.png" alt="Avatar" width="80" height="80" style="border-radius: 50%" ; /></td>
                    }

                <td style="padding-top: 30px;">@person.Name</td>
                <td style="padding-top: 30px;">@person.Surname</td>
                <td style="padding-top: 30px;">@person.BirthDate.ToShortDateString()</td>
                <td style="padding-top: 30px;">@person.Age</td>
                <td style="padding-top: 30px;">@person.Gender</td>
                <td>
                        <a href="/Tablo/Edit/@person.Id" class="btn btn-dark" style="margin-top: 20px;">Edit</a>
                </td>

                </tr>
            }
        </tbody>
    </table>



    <a asp-page="./Tablo"
        asp-route-sortOrder="@Model.CurrentSort"
       asp-route-pageIndex="@(Model.Persons.PageIndex - 1)"
        asp-route-currentFilter="@Model.CurrentFilter"
        class="btn btn-primary @prevDisabled">
        Previous
    </a>
    <a asp-page="./Tablo"
        asp-route-sortOrder="@Model.CurrentSort"
       asp-route-pageIndex="@(Model.Persons.PageIndex + 1)"
        asp-route-currentFilter="@Model.CurrentFilter"
        class="btn btn-primary @nextDisabled">
        Next
    </a>
}




 